on: [push]

jobs:
  backup_job:
    runs-on: ubuntu-latest
    name: Backup source code to Arweave
    steps:
      - name: Backup
        id: backup
        uses: dhaiwat10/arweave-repo-backup-gh-action@v0.13
        with:
          arweaveWalletKey: ${{ secrets.ARWEAVE_WALLET_KEY }}
      - name: Log the TX ID
        run: echo "The TX ID is ${{ steps.backup.outputs.txId }}"
